script:
- npm install --no-save eslint-plugin-import@^2.7.0 eslint-plugin-jsx-a11y@^5.1.1 eslint-plugin-react@^7.1.0 @takram/planck-core @takram/planck-event
- npm run test
language: node_js
node_js:
- 8.1
notifications:
  slack:
    secure: SXPyJZBL6HGYN4OFLElQ2FJrTZzrbCrJrsInmmaS7Zgr6b3dAdYeslBfcuK/q5ToiouaaTYjBM68YAc6SeSvyPILwgIuSsntHIpVQX3PFD8sNVlFooOjMyO9UdynjWcLLX8e03bY43CYwGjj+QWSYg8Mfswrmzo5IBTeS9rckPHTvTtwDoIryXsEc/4PJVpWTVKlpPhNb9eDkCX1T35YVkSzkd/hw/Q7481fEMcXUXTG6rIetl/6THQM+XNWMcjgwt0fnoXGUD7z3zXUbUyVGco8cmXhbqz8LMAHgYcXAu7N2XDTittdsyszjZm37FTZgkQfaTYcHhYs4+MTTXbf1FaFJK66BgqkY7ikG2UFU1Zm584h5V1YKtD2czx7jveshd1SMxNhb0xS0hiNCM0P7qBpUq44xw0ZY85jo8c2LDX1tVWgHVx/UMDs8yINvbWED4Nlq3QtXggEoixQH4/bTMPEbVjxnW59OJCIGmZSxkNLDpfqeBuZyA272cBKwZbOqadaoqawAg8HrGLJwojc6wKTZptyj3XPnYVKYd+hXHN5fObDvPZ5x2MHzSO87LAQegBueRqeHFDShCPKKk5qbtceRO8wDzGLm55wzudgjN0rKC1cesi7bmiTZeSwx/4CSR/9e0grJvxzQYDgdnD/ag43R8ZWf+q7wRe+lq2uQZg=
